image: alpine:latest

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - unit-test
  - release

include:
  - template: Code-Quality.gitlab-ci.yml
  - local: '/.gitlab-ci/Jobs/cloud_php_unit_tests.yml'
  - local: '/.gitlab-ci/Jobs/style_check.yml'

code_quality:
  stage: unit-test
