version: '3.4'
services:
  db:
    image: mariadb:10.3
    env_file:
      - docker/env/mysql.env
    tmpfs:
      - /var/lib/mysql
    ports:
      - 3306:3306
  redis-master:
    image: redis
    ports:
      - 6379
  passbolt-cloud:
    build:
      context: .
    depends_on:
      - db
      - redis-master
    env_file:
      - docker/env/local.env
      - docker/env/passbolt-cloud.env
    volumes:
      - images_volume:/var/www/passbolt/webroot/img/public/images
      - ${PWD}/config/gpg/unsecure.key:/var/www/passbolt/config/gpg/serverkey.key
      - ${PWD}/config/gpg/unsecure_private.key:/var/www/passbolt/config/gpg/serverkey_private.key
      - ${PWD}/docker/conf/ssl/server.crt:/etc/ssl/certs/passbolt/server.crt
      - ${PWD}/docker/conf/ssl/server-key.pem:/etc/ssl/certs/passbolt/server-key.pem
      - ${PWD}/docker/scripts/wait-for.sh:/usr/bin/wait-for.sh
      - ${PWD}:/var/www/passbolt
    command:
      - /bin/bash
      - -c
      - |
        ln -s /var/www/passbolt/docker/conf/passbolt.php /var/www/passbolt/config/passbolt.php
        ln -s /var/www/passbolt/docker/conf/app.php /var/www/passbolt/config/app.php
        echo "$$CLOUD_ADMIN_DEFAULT_HOST $$PASSBOLT_SCRIPT_CATALOG_HOST" >> /etc/hosts
        if [ "$$PHP_COMPOSER" ]; then
          apt-get update
          apt-get install -y git unzip nano
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          mv composer.phar /usr/bin/composer
          composer install
          rm -rf cache
          rm -rf pear
        fi
        /usr/bin/wait-for.sh db:3306 -- mysql -h db -u root -ptest -e "create database if not exists pb_org_acme;"
        mysql -h db -u root -ptest -e "create database if not exists passbolt_cloud_email_queue;"
        mysql -h db -u root -ptest -e "create database if not exists pb_org_acme_test;"
        mysql -h db -u root -ptest -e "create database if not exists passbolt_cloud_email_queue_test;"
        mysql -h db -u root -ptest -e "grant all on *.* to passbolt@'%' identified by 'P4ssb0lt';"
        su -c "./bin/cake migrations migrate -p EmailQueue --connection emailQueue" -s /bin/bash www-data
        su -c "gpg --import /var/www/passbolt/config/gpg/serverkey_private.key" -s /bin/bash www-data
        su -c "php ./bin/passbolt/migrate_orgs.php" -s /bin/bash www-data
        su -c "./bin/cake passbolt migrate --org=acme" -s /bin/bash www-data
        su -c "./bin/cake passbolt register_user --org=acme --first-name=Wile --last-name=Coyote --username=coyote@cloud.passbolt.local --role=admin" -s /bin/bash www-data
        /docker-entrypoint.sh
    ports:
      - 80:80
      - 443:443

volumes:
  database_volume:
  images_volume:
