version: '3.4'
services:
  db:
    image: mariadb:10.3
    env_file:
      - env/mysql.env
    volumes:
      - database_volume:/var/lib/mysql
    ports:
      - 3306
  redis:
    image: redis
    ports:
      - 6379

  passbolt:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - images_volume:/var/www/passbolt/webroot/img/public/images
      - ./scripts/wait-for.sh:/usr/bin/wait-for.sh
      - ${PWD}/docker/app.php:/var/www/passbolt/config/app.php
      - ${PWD}/docker/passbolt.php:/var/www/passbolt/config/passbolt.php
    command: ["/usr/bin/wait-for.sh", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 80:80
      - 443:443

volumes:
  database_volume:
  images_volume:
