version: '3.4'
services:
  db:
    image: mariadb:10.3
    env_file:
      - docker/env/mysql.env
    volumes:
      - database_volume:/var/lib/mysql
    ports:
      - 3306
  redis:
    image: redis
    ports:
      - 6379

  passbolt:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - images_volume:/var/www/passbolt/webroot/img/public/images
      - ${PWD}/docker/conf/ssl/server.crt:/etc/ssl/certs/passbolt/server.crt
      - ${PWD}/docker/conf/ssl/server-key.pem:/etc/ssl/certs/passbolt/server-key.pem
      - ${PWD}/docker/scripts/wait-for.sh:/usr/bin/wait-for.sh
      - ${PWD}/docker/conf/app.php:/var/www/passbolt/config/app.php
      - ${PWD}/docker/conf/passbolt.php:/var/www/passbolt/config/passbolt.php
    command:
      - /bin/bash
      - -c
      - |
        /usr/bin/wait-for.sh db:3306 -- mysql -h db -u root -ptest -e "create database if not exists email_queue;" \
        && /docker-entrypoint.sh
    ports:
      - 80:80
      - 443:443

volumes:
  database_volume:
  images_volume:
