help_site_notes:
  stage: release
  image: gitlab/glab
  script:
    - bash .gitlab-ci/scripts/bin/help_site.sh
  rules:
    #- if: '$CI_COMMIT_TAG && $CI_COMMIT_BRANCH =~ "master|release|feature/PB-24575-release-notes"'
    - if: '$CI_COMMIT_BRANCH == "feature/PB-24575-release-notes"'
      when: always
