release_notes:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  release:
    description: './RELEASE_NOTES.md'
    tag_name: $CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_BRANCH =~ "master|release"'
      when: on_success
  script: echo "Creating relase notes for $CI_COMMIT_TAG"
  stage: release
