release_notes:
  release:
    description: './RELEASE_NOTES.md'
    tag_name: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  script: echo "Creating relase notes for $CI_COMMIT_TAG"
  stage: release
