release_notes:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  release:
    description: './RELEASE_NOTES.md'
    tag_name: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  script: |
    source .gitlab-ci/scripts/bin/set-env.sh "$CI_COMMIT_TAG"
    if is_release_candidate "$CI_COMMIT_TAG"; then
      echo "The tag is for a release candidate. Skipping release notes creation..."
      exit 0
    fi
    echo "Creating relase notes for $CI_COMMIT_TAG"
  stage: release
