release_notes:
  image: debian:bullseye-slim
  release:
    description: './RELEASE_NOTES.md'
    tag_name: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  script: |
    source .gitlab-ci/scripts/bin/set-env.sh "$CI_COMMIT_TAG"
    if is_release_candidate "$tag"; then
      echo "The tag is for a release candidate. Skipping release notes creation..."
      exit 0
    fi
    apt update && apt install -y git curl
    curl -L https://gitlab.com/gitlab-org/cli/-/releases/v1.30.0/downloads/glab_1.30.0_Linux_x86_64.deb  --output glab.deb
    dpkg -i glab.deb
  stage: release
