release_notes:
  stage: release
  image: gitlab/glab
  script:
    - apk --update add gpg gpg-agent
    - bash .gitlab-ci/scripts/bin/release.sh gitlab
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
