<?php
/**
 * Passbolt ~ Open source password manager for teams
 * Copyright (c) Passbolt SARL (https://www.passbolt.com)
 *
 * Licensed under GNU Affero General Public License version 3 of the or any later version.
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Passbolt SARL (https://www.passbolt.com)
 * @license       https://opensource.org/licenses/AGPL-3.0 AGPL License
 * @link          https://www.passbolt.com Passbolt(tm)
 * @since         2.0.0
 */
/**
 * PASSBOLT CONFIGURATION FILE
 *
 * This is a generated configuration file, which was generated by the passbolt web installer.
 *
 * To see all available options, you can refer to the default.php file, or replace this file
 * by a copy of passbolt.default.php
 * Do not modify default.php or you may break your upgrade process.
 *
 * Read more about how to install passbolt: https://www.passbolt.com/help/tech/install
 * Any issue, check out our FAQ: https://www.passbolt.com/faq
 * An installation issue? Ask for help to the community: https://community.passbolt.com/
 */
return [
    'debug' => false,
    'App' => [
        // A base URL to use for absolute links.
        // The url where the passbolt instance will be reachable to your end users.
        // This information is need to render images in emails for example
        'fullBaseUrl' => env('APP_FULL_BASE_URL'),
    ],

    // Database configuration.
    'Datasources' => [
        'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => env('DATASOURCES_DEFAULT_DRIVER', 'Cake\Database\Driver\Mysql'),
            'persistent' => false,
            'host' => env('DATASOURCES_DEFAULT_HOST', 'localhost'),
            'port' => env('DATASOURCES_DEFAULT_PORT', 3306),
            /**
             * CakePHP will use the default DB port based on the driver selected
             * MySQL on MAMP uses port 8889, MAMP users will want to uncomment
             * the following line and set the port accordingly
             */
            //'port' => 'non_standard_port_number',
            'username' => env('DATASOURCES_DEFAULT_USERNAME', ''),
            'password' => env('DATASOURCES_DEFAULT_PASSWORD', ''),
            'database' => env('DATASOURCES_DEFAULT_DATABASE', ''),
            'ssl_key' => env('DATASOURCES_DEFAULT_SSL_KEY', ''),
            'ssl_cert' => env('DATASOURCES_DEFAULT_SSL_CERT', ''),
            'ssl_ca' => env('DATASOURCES_DEFAULT_SSL_CA', ''),
            'encoding' => 'utf8mb4',
            'timezone' => 'UTC',
            'flags' => [],
            'cacheMetadata' => true,
            'log' => false,
            'quoteIdentifiers' => false,
            'url' => env('DATASOURCES_DEFAULT_URL', null),
        ],
        'emailQueue' => [
            'className' => 'Cake\Database\Connection',
            'driver' => env('DATASOURCES_EMAILQUEUE_DRIVER', 'Cake\Database\Driver\Mysql'),
            'persistent' => false,
            'host' => env('DATASOURCES_EMAILQUEUE_HOST', 'localhost'),
            'port' => env('DATASOURCES_EMAILQUEUE_PORT', 3306),
            /**
             * CakePHP will use the default DB port based on the driver selected
             * MySQL on MAMP uses port 8889, MAMP users will want to uncomment
             * the following line and set the port accordingly
             */
            //'port' => 'non_standard_port_number',
            'username' => env('DATASOURCES_EMAILQUEUE_USERNAME', ''),
            'password' => env('DATASOURCES_EMAILQUEUE_PASSWORD', ''),
            'database' => env('DATASOURCES_EMAILQUEUE_DATABASE', ''),
            'ssl_key' => env('DATASOURCES_EMAILQUEUE_SSL_KEY', ''),
            'ssl_cert' => env('DATASOURCES_EMAILQUEUE_SSL_CERT', ''),
            'ssl_ca' => env('DATASOURCES_EMAILQUEUE_SSL_CA', ''),
            'encoding' => 'utf8mb4',
            'timezone' => 'UTC',
            'flags' => [],
            'cacheMetadata' => true,
            'log' => false,
            'quoteIdentifiers' => false,
            'url' => env('DATASOURCES_EMAILQUEUE_URL', null),
        ],
    ],

    // Email configuration.
    'EmailTransport' => [
        'default' => [
            'host' => '',
            'port' => 587,
            'username' => '',
            'password' => '',
            // Is this a secure connection? true if yes, null if no.
            'tls' => true,
            //'timeout' => 30,
            //'client' => null,
            //'url' => null,
        ],
    ],
    'Email' => [
        'default' => [
            // Defines the default name and email of the sender of the emails.
            'from' => ['no-reply@passbolt.com' => 'Passbolt'],
            //'charset' => 'utf-8',
            //'headerCharset' => 'utf-8',
        ],
    ],
    // Which connection to use with emailQueue.
    'EmailQueue' => [
        'datasource' => 'emailQueue',
    ],
    'passbolt' => [
        // GPG Configuration.
        // The keyring must to be owned and accessible by the webserver user.
        // Example: www-data user on Debian
        //'gpg' => [
        //    // Main server key.
        //    'serverKey' => [
        //        // Server private key fingerprint.
        //        'fingerprint' => '7EE80D0A883A535BA6A13950F468D047F09FC8CA',
        //        'public' => CONFIG . DS . 'gpg' . DS . 'serverkey.asc',
        //        'private' => CONFIG . DS . 'gpg' . DS . 'serverkey_private.asc',
        //    ],
        //],
        'registration' => [
            'public' => false,
        ],
        'ssl' => [
            'force' => true,
        ],
        'multiTenant' => [
            'configDir' => '/home/www-data',
            'auth' => [
                'secret' => ''
            ],
            'rootRedirectUrl' => '',
        ],
    ],
];
