<?php
/**
 * Passbolt ~ Open source password manager for teams
 * Copyright (c) Passbolt SARL (https://www.passbolt.com)
 *
 * Licensed under GNU Affero General Public License version 3 of the or any later version.
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Passbolt SARL (https://www.passbolt.com)
 * @license       https://opensource.org/licenses/AGPL-3.0 AGPL License
 * @link          https://www.passbolt.com Passbolt(tm)
 * @since         2.0.0
 */
/**
 * PASSBOLT CONFIGURATION FILE
 *
 * This is a generated configuration file, which was generated by the passbolt web installer.
 *
 * To see all available options, you can refer to the default.php file, or replace this file
 * by a copy of passbolt.default.php
 * Do not modify default.php or you may break your upgrade process.
 *
 * Read more about how to install passbolt: https://www.passbolt.com/help/tech/install
 * Any issue, check out our FAQ: https://www.passbolt.com/faq
 * An installation issue? Ask for help to the community: https://community.passbolt.com/
 */
return [
    // Database configuration.
    'Datasources' => [
        'emailQueue' => [
            'className' => 'Cake\Database\Connection',
            'driver' => env('DATASOURCES_EMAILQUEUE_DRIVER', 'Cake\Database\Driver\Mysql'),
            'persistent' => false,
            'host' => env('DATASOURCES_EMAILQUEUE_HOST', 'localhost'),
            'port' => env('DATASOURCES_EMAILQUEUE_PORT', 3306),
            'username' => env('DATASOURCES_EMAILQUEUE_USERNAME', ''),
            'password' => env('DATASOURCES_EMAILQUEUE_PASSWORD', ''),
            'database' => env('DATASOURCES_EMAILQUEUE_DATABASE', ''),
            'ssl_key' => env('DATASOURCES_EMAILQUEUE_SSL_KEY', ''),
            'ssl_cert' => env('DATASOURCES_EMAILQUEUE_SSL_CERT', ''),
            'ssl_ca' => env('DATASOURCES_EMAILQUEUE_SSL_CA', ''),
            'encoding' => 'utf8mb4',
            'timezone' => 'UTC',
            'flags' => [],
            'cacheMetadata' => true,
            'log' => false,
            'quoteIdentifiers' => false,
            'url' => env('DATASOURCES_EMAILQUEUE_URL', null),
        ],
        'test_emailQueue' => [
            'className' => 'Cake\Database\Connection',
            'driver' => env('DATASOURCES_TEST_DRIVER', 'Cake\Database\Driver\Mysql'),
            'persistent' => false,
            'host' => env('DATASOURCES_TEST_HOST', 'localhost'),
            'port' => env('DATASOURCES_TEST_PORT', 3306),
            'username' => env('DATASOURCES_TEST_USERNAME', 'my_app'),
            'password' => env('DATASOURCES_TEST_PASSWORD', 'secret'),
            'database' => env('DATASOURCES_TEST_DATABASE', 'my_app'),
            'ssl_key' => env('DATASOURCES_TEST_SSL_KEY', ''),
            'ssl_cert' => env('DATASOURCES_TEST_SSL_CERT', ''),
            'ssl_ca' => env('DATASOURCES_TEST_SSL_CA', ''),
            'encoding' => 'utf8mb4',
            'timezone' => 'UTC',
            'cacheMetadata' => true,
            'quoteIdentifiers' => false,
            'log' => false,
            //'init' => ['SET GLOBAL innodb_stats_on_metadata = 0'],
            'url' => env('DATASOURCES_TEST_URL', null),
        ],
    ],
    'Email' => [
        'default' => [
            // Defines the default name and email of the sender of the emails.
            'from' => ['no-reply@passbolt.com' => 'Passbolt'],
            //'charset' => 'utf-8',
            //'headerCharset' => 'utf-8',
        ],
    ],
    // Which connection to use with emailQueue.
    'EmailQueue' => [
        'datasource' => 'emailQueue',
    ]
];
