name: Create Release

on:
    push:
        tags:
            - "*.*.*"

jobs:
    build:
        name: Create release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              name: Create Release
              run: gh release create v1.2.3 --generate-notes
              #- name: Checkout help site
              #  uses: actions/checkout@v3
              #  with:
              #      repository: dlen/passbolt_help
              #      token: ${{ secrets.GH_TOKEN}}
              #      path: passbolt_help
              #- name: Create help site release notes file
              #  run: |
              #      cat << EOF >> passbolt_help/_releases/ce/v${{ github.ref_name }}.md
              #      ---
              #      title: $(grep name config/version.php | awk -F "'" '{print $4}')
              #      slug: $(grep name config/version.php | awk -F "'" '{print $4}' | tr ' ' '_' | tr '[:upper:]' '[:lower:]')
              #      layout: release
              #      categories: releases ce
              #      version: v${{ github.ref_name }}
              #      product: ce
              #      song: https://youtu.be/qw6ZX07NZSM
              #      quote: $(grep name config/version.php | awk -F "'" '{print $4}')
              #      permalink: /releases/ce/$(grep name config/version.php | awk -F "'" '{print $4}' | tr ' ' '_' | tr '[:upper:]' '[:lower:]')
              #      date: $(date +'%Y-%m-%d')
              #      ---
              #      EOF
              #      cat RELEASE_NOTES.md >> passbolt_help/_releases/ce/v${{ github.ref_name }}.md
              #- name: Publish release
              #  uses: stefanzweifel/git-auto-commit-action@v4
              #  with:
              #      commit_message: "ci: New release notes for CE ${{ github.ref_name }}"
              #      commit_user_email: contact@passbolt.com
              #      commit_user_name: GitHub Actions
              #      repository: ./passbolt_help
              #      continue-on-error: false
