name: Create Release

on:
    push:
        tags:
            - "*.*.*"

jobs:
    build:
        name: Create release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Extract release notes
              id: extract-release-notes
              uses: ffurrer2/extract-release-notes@v1
              with:
                  release_notes_file: RELEASE_NOTES.md
            - name: Create release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
                  draft: false
                  prerelease: false
                  body: ${{ steps.extract-release-notes.outputs.release_notes }}
            - name: Checkout help site
              uses: actions/checkout@v3
              with:
                  repository: dlen/passbolt_help
                  path: passbolt_help
            - name: Create help site release notes file
              run: |
                  cat << EOF >> passbolt_help/_releases/ce/v${{ github.ref_name }}.md
                  ---
                  title: $(grep name config/version.php | awk -F "'" '{print $4}')
                  slug: $(grep name config/version.php | awk -F "'" '{print $4}' | tr ' ' '_' | tr '[:upper:]' '[:lower:]')
                  layout: release
                  categories: releases ce
                  version: v${{ github.ref_name }}
                  product: ce
                  song: https://youtu.be/qw6ZX07NZSM
                  quote: $(grep name config/version.php | awk -F "'" '{print $4}')
                  permalink: /releases/ce/$(grep name config/version.php | awk -F "'" '{print $4}' | tr ' ' '_' | tr '[:upper:]' '[:lower:]')
                  date: $(date +'%Y-%m-%d')
                  ---
                  EOF
                  cat RELEASE_NOTES.md >> passbolt_help/_releases/ce/v${{ github.ref_name }}.md
                  cd passbolt_help
                  git config --global user.name "release bot"
                  git config --global user.email "contact@passbolt.com"
                  git add -A
                  git commit -m "New release notes for CE ${{ github.ref_name }}"
                  git push
